resolver: lts-17.14
extra-deps:
  - acc-0.1.3
  - attoparsec-data-1.0.5.1
  - attoparsec-time-1.0.1.1
  - domain-core-0.1
  - profunctors-5.6.2
  - rebase-1.13
  - rerebase-1.13
  - th-lego-0.2.3
  - yaml-unscrambler-0.1.0.2
