resolver: nightly-2021-06-24
extra-deps:
  - acc-0.1.3
  - attoparsec-data-1.0.5.2
  - attoparsec-time-1.0.1.2
  - domain-core-0.1
  - th-lego-0.2.3
  - yaml-unscrambler-0.1.0.3
  - template-haskell-compat-v0208-0.1.6
